spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 180825172102-mqlbn4p6l6utqknd2l87itvm015vbs9i.apps.googleusercontent.com
            client-secret: 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